// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKRDPbsE77N1JPXbWjCYMczTpQM20uz1o',
    appId: '1:623607458675:web:e8390704de0f544da37306',
    messagingSenderId: '623607458675',
    projectId: 'thread-thread-threads',
    authDomain: 'thread-thread-threads.firebaseapp.com',
    storageBucket: 'thread-thread-threads.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApiOeqQv74Rt92uxP1X3dfREEHQnB7q9c',
    appId: '1:623607458675:android:531d7558f1760891a37306',
    messagingSenderId: '623607458675',
    projectId: 'thread-thread-threads',
    storageBucket: 'thread-thread-threads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Rl5wYtagBZ8EFkolGFszgDcgn-o9wlw',
    appId: '1:623607458675:ios:64afc421844490b6a37306',
    messagingSenderId: '623607458675',
    projectId: 'thread-thread-threads',
    storageBucket: 'thread-thread-threads.firebasestorage.app',
    iosBundleId: 'com.example.thread',
  );
}
